env:
  global:
    secure: qCXBI+uQIhWuV3wThMkEaWOL95ATVTQ3C5JdlRbQDVjwjl4aabC5FAmQYsrzlPSalqtUqa4SgILSSDo/SIjrZ5lsRBjgG6inWrbbGWaUyyr+cN2+jKDy5pAikDpcQkWoNa4GNqkRumm94C9MtJyq69LxVNpixm7104VcerERDQCt2WMqKcpExSLfn0zozoWexnh0YwcDt2aUVUT++TE4VjoMXSXcewWxrP5nP8Kko6J3ZtbX0MIZxgoManzyYG84imXKFEsi/3lxox7msiMliY6tBa9AeQ0R9FpvFaYFlfQ6dfCY9nF2I4VcsQHu9qJOfQR32vTGp94rbALNCeGnS0rBRF5uZoEvdVzvs3RJCNJiGGn2/KnknSwGEVpSZN/JexjJqlIEpxAoxdlsqfVtCPq3eoZuItiaiYEbA9pw0xWTxEnJpx0y2kTYkDKkYam6SNm/0+or8ltxDhVElvusju05vjRE6uPZgzmO03pwFbctq+UyNsgEudgkv73ECv3MmbrCvHX6micbqHlCZxHjOBaP8qfsHEpbJglUpZTFKkUYnEP2DojcAYSFhrD8k2CiBXdtGlAyJYoCrhs7gA+nhF9vX49KvYHjjM3fhIr8jvL+fX9wql/w0ov53b8Qn9KfRKfQw8yNhq0sfRY63BUEjMB2nykHBfvjgP/bTd0SDb0=

dist: bionic
language: c
compiler: clang
before_install:
  - sudo apt-get update
  - sudo apt-get -y install cmake liblua5.3-dev libiniparser-dev libsdl2-dev
  - sudo apt-get -y install libcunit1-dev libblocksruntime-dev doxygen libdispatch-dev

install:
  - git clone git://github.com/shamazmazum/vn3d.git vn3d
  - pushd vn3d && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && sudo make install
  - popd

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/build/install $TRAVIS_BUILD_DIR

script:
  - make
  - make check
  - make doc
  - sudo make install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "$TRAVIS_BUILD_DIR/build/doc/html"
  edge: true
  on:
    branch: master
