name: CI

on: [push]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Checkout vn3d
        uses: actions/checkout@v2
        with:
          repository: shamazmazum/vn3d
          path: vn3d
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen cmake liblua5.3-dev libiniparser-dev
          sudo apt-get install libsdl2-dev libcunit1-dev libblocksruntime-dev
          sudo apt-get install libdispatch-dev
      - name: Install dependencies (2)
        run: |
          mkdir -p $GITHUB_WORKSPACE/vn3d/build && cd $GITHUB_WORKSPACE/vn3d/build
          cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && sudo make install
      - name: Configure
        run: |
          mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build
          cmake -DCMAKE_BUILD_TYPE=RELEASE $GITHUB_WORKSPACE
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/build
          make doc
      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/doc/html
